[build-system]
requires = ["maturin>=1.11.5"]
build-backend = "maturin"

[tool.maturin]
# This tells maturin:
# - build a native Python extension
# - using Cargo
# - enabling the "python" feature
bindings = "pyo3"
features = ["python"]